import type { Metadata } from "next";
import "./globals.css";
import { UserAuthContextProvider } from "../context/UserAuthContext";
import { ThemeProvider } from "@/components/theme-provider";
export const metadata: Metadata = {
  title: "EQtrade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <UserAuthContextProvider>{children}</UserAuthContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
